# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/Desktop/7166CEM

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/Desktop/7166CEM

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Desktop/7166CEM/CMakeFiles /home/pi/Desktop/7166CEM/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Desktop/7166CEM/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named candata

# Build rule for target.
candata: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 candata
.PHONY : candata

# fast build rule for target.
candata/fast:
	$(MAKE) -f CMakeFiles/candata.dir/build.make CMakeFiles/candata.dir/build
.PHONY : candata/fast

#=============================================================================
# Target rules for targets named Application

# Build rule for target.
Application: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Application
.PHONY : Application

# fast build rule for target.
Application/fast:
	$(MAKE) -f CMakeFiles/Application.dir/build.make CMakeFiles/Application.dir/build
.PHONY : Application/fast

#=============================================================================
# Target rules for targets named docs

# Build rule for target.
docs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 docs
.PHONY : docs

# fast build rule for target.
docs/fast:
	$(MAKE) -f Docs/CMakeFiles/docs.dir/build.make Docs/CMakeFiles/docs.dir/build
.PHONY : docs/fast

#=============================================================================
# Target rules for targets named Test_VCUWheelSpeedFrameProcess

# Build rule for target.
Test_VCUWheelSpeedFrameProcess: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test_VCUWheelSpeedFrameProcess
.PHONY : Test_VCUWheelSpeedFrameProcess

# fast build rule for target.
Test_VCUWheelSpeedFrameProcess/fast:
	$(MAKE) -f Test/CMakeFiles/Test_VCUWheelSpeedFrameProcess.dir/build.make Test/CMakeFiles/Test_VCUWheelSpeedFrameProcess.dir/build
.PHONY : Test_VCUWheelSpeedFrameProcess/fast

#=============================================================================
# Target rules for targets named Test_RearTorqueLimit

# Build rule for target.
Test_RearTorqueLimit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test_RearTorqueLimit
.PHONY : Test_RearTorqueLimit

# fast build rule for target.
Test_RearTorqueLimit/fast:
	$(MAKE) -f Test/CMakeFiles/Test_RearTorqueLimit.dir/build.make Test/CMakeFiles/Test_RearTorqueLimit.dir/build
.PHONY : Test_RearTorqueLimit/fast

#=============================================================================
# Target rules for targets named Test_RearCurrentCalculation

# Build rule for target.
Test_RearCurrentCalculation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test_RearCurrentCalculation
.PHONY : Test_RearCurrentCalculation

# fast build rule for target.
Test_RearCurrentCalculation/fast:
	$(MAKE) -f Test/CMakeFiles/Test_RearCurrentCalculation.dir/build.make Test/CMakeFiles/Test_RearCurrentCalculation.dir/build
.PHONY : Test_RearCurrentCalculation/fast

#=============================================================================
# Target rules for targets named Test_MotorCurrentFrameProcess

# Build rule for target.
Test_MotorCurrentFrameProcess: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test_MotorCurrentFrameProcess
.PHONY : Test_MotorCurrentFrameProcess

# fast build rule for target.
Test_MotorCurrentFrameProcess/fast:
	$(MAKE) -f Test/CMakeFiles/Test_MotorCurrentFrameProcess.dir/build.make Test/CMakeFiles/Test_MotorCurrentFrameProcess.dir/build
.PHONY : Test_MotorCurrentFrameProcess/fast

#=============================================================================
# Target rules for targets named Test_BatteryFrameProcessing

# Build rule for target.
Test_BatteryFrameProcessing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test_BatteryFrameProcessing
.PHONY : Test_BatteryFrameProcessing

# fast build rule for target.
Test_BatteryFrameProcessing/fast:
	$(MAKE) -f Test/CMakeFiles/Test_BatteryFrameProcessing.dir/build.make Test/CMakeFiles/Test_BatteryFrameProcessing.dir/build
.PHONY : Test_BatteryFrameProcessing/fast

#=============================================================================
# Target rules for targets named Test_DriveRequestFrameProcessing

# Build rule for target.
Test_DriveRequestFrameProcessing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test_DriveRequestFrameProcessing
.PHONY : Test_DriveRequestFrameProcessing

# fast build rule for target.
Test_DriveRequestFrameProcessing/fast:
	$(MAKE) -f Test/CMakeFiles/Test_DriveRequestFrameProcessing.dir/build.make Test/CMakeFiles/Test_DriveRequestFrameProcessing.dir/build
.PHONY : Test_DriveRequestFrameProcessing/fast

#=============================================================================
# Target rules for targets named Test_GenerateCANFrame

# Build rule for target.
Test_GenerateCANFrame: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test_GenerateCANFrame
.PHONY : Test_GenerateCANFrame

# fast build rule for target.
Test_GenerateCANFrame/fast:
	$(MAKE) -f Test/CMakeFiles/Test_GenerateCANFrame.dir/build.make Test/CMakeFiles/Test_GenerateCANFrame.dir/build
.PHONY : Test_GenerateCANFrame/fast

#=============================================================================
# Target rules for targets named Test_FrontCurrentCalculation

# Build rule for target.
Test_FrontCurrentCalculation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test_FrontCurrentCalculation
.PHONY : Test_FrontCurrentCalculation

# fast build rule for target.
Test_FrontCurrentCalculation/fast:
	$(MAKE) -f Test/CMakeFiles/Test_FrontCurrentCalculation.dir/build.make Test/CMakeFiles/Test_FrontCurrentCalculation.dir/build
.PHONY : Test_FrontCurrentCalculation/fast

#=============================================================================
# Target rules for targets named Test_FrontTorqueLimit

# Build rule for target.
Test_FrontTorqueLimit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test_FrontTorqueLimit
.PHONY : Test_FrontTorqueLimit

# fast build rule for target.
Test_FrontTorqueLimit/fast:
	$(MAKE) -f Test/CMakeFiles/Test_FrontTorqueLimit.dir/build.make Test/CMakeFiles/Test_FrontTorqueLimit.dir/build
.PHONY : Test_FrontTorqueLimit/fast

Src/Application.o: Src/Application.c.o

.PHONY : Src/Application.o

# target to build an object file
Src/Application.c.o:
	$(MAKE) -f CMakeFiles/Application.dir/build.make CMakeFiles/Application.dir/Src/Application.c.o
.PHONY : Src/Application.c.o

Src/Application.i: Src/Application.c.i

.PHONY : Src/Application.i

# target to preprocess a source file
Src/Application.c.i:
	$(MAKE) -f CMakeFiles/Application.dir/build.make CMakeFiles/Application.dir/Src/Application.c.i
.PHONY : Src/Application.c.i

Src/Application.s: Src/Application.c.s

.PHONY : Src/Application.s

# target to generate assembly for a file
Src/Application.c.s:
	$(MAKE) -f CMakeFiles/Application.dir/build.make CMakeFiles/Application.dir/Src/Application.c.s
.PHONY : Src/Application.c.s

Src_autogen/candata.o: Src_autogen/candata.c.o

.PHONY : Src_autogen/candata.o

# target to build an object file
Src_autogen/candata.c.o:
	$(MAKE) -f CMakeFiles/candata.dir/build.make CMakeFiles/candata.dir/Src_autogen/candata.c.o
.PHONY : Src_autogen/candata.c.o

Src_autogen/candata.i: Src_autogen/candata.c.i

.PHONY : Src_autogen/candata.i

# target to preprocess a source file
Src_autogen/candata.c.i:
	$(MAKE) -f CMakeFiles/candata.dir/build.make CMakeFiles/candata.dir/Src_autogen/candata.c.i
.PHONY : Src_autogen/candata.c.i

Src_autogen/candata.s: Src_autogen/candata.c.s

.PHONY : Src_autogen/candata.s

# target to generate assembly for a file
Src_autogen/candata.c.s:
	$(MAKE) -f CMakeFiles/candata.dir/build.make CMakeFiles/candata.dir/Src_autogen/candata.c.s
.PHONY : Src_autogen/candata.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... rebuild_cache"
	@echo "... candata"
	@echo "... Application"
	@echo "... docs"
	@echo "... Test_VCUWheelSpeedFrameProcess"
	@echo "... Test_RearTorqueLimit"
	@echo "... Test_RearCurrentCalculation"
	@echo "... Test_MotorCurrentFrameProcess"
	@echo "... Test_BatteryFrameProcessing"
	@echo "... Test_DriveRequestFrameProcessing"
	@echo "... Test_GenerateCANFrame"
	@echo "... Test_FrontCurrentCalculation"
	@echo "... Test_FrontTorqueLimit"
	@echo "... Src/Application.o"
	@echo "... Src/Application.i"
	@echo "... Src/Application.s"
	@echo "... Src_autogen/candata.o"
	@echo "... Src_autogen/candata.i"
	@echo "... Src_autogen/candata.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

