# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/Desktop/7166CEM

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/Desktop/7166CEM

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Desktop/7166CEM/CMakeFiles /home/pi/Desktop/7166CEM/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Desktop/7166CEM/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named candata

# Build rule for target.
candata: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 candata
.PHONY : candata

# fast build rule for target.
candata/fast:
	$(MAKE) -f CMakeFiles/candata.dir/build.make CMakeFiles/candata.dir/build
.PHONY : candata/fast

#=============================================================================
# Target rules for targets named Application

# Build rule for target.
Application: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Application
.PHONY : Application

# fast build rule for target.
Application/fast:
	$(MAKE) -f CMakeFiles/Application.dir/build.make CMakeFiles/Application.dir/build
.PHONY : Application/fast

#=============================================================================
# Target rules for targets named Unity

# Build rule for target.
Unity: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Unity
.PHONY : Unity

# fast build rule for target.
Unity/fast:
	$(MAKE) -f Test/CMakeFiles/Unity.dir/build.make Test/CMakeFiles/Unity.dir/build
.PHONY : Unity/fast

#=============================================================================
# Target rules for targets named TestApplication

# Build rule for target.
TestApplication: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestApplication
.PHONY : TestApplication

# fast build rule for target.
TestApplication/fast:
	$(MAKE) -f Test/CMakeFiles/TestApplication.dir/build.make Test/CMakeFiles/TestApplication.dir/build
.PHONY : TestApplication/fast

Src/Application.o: Src/Application.c.o

.PHONY : Src/Application.o

# target to build an object file
Src/Application.c.o:
	$(MAKE) -f CMakeFiles/Application.dir/build.make CMakeFiles/Application.dir/Src/Application.c.o
.PHONY : Src/Application.c.o

Src/Application.i: Src/Application.c.i

.PHONY : Src/Application.i

# target to preprocess a source file
Src/Application.c.i:
	$(MAKE) -f CMakeFiles/Application.dir/build.make CMakeFiles/Application.dir/Src/Application.c.i
.PHONY : Src/Application.c.i

Src/Application.s: Src/Application.c.s

.PHONY : Src/Application.s

# target to generate assembly for a file
Src/Application.c.s:
	$(MAKE) -f CMakeFiles/Application.dir/build.make CMakeFiles/Application.dir/Src/Application.c.s
.PHONY : Src/Application.c.s

Src/candata.o: Src/candata.c.o

.PHONY : Src/candata.o

# target to build an object file
Src/candata.c.o:
	$(MAKE) -f CMakeFiles/candata.dir/build.make CMakeFiles/candata.dir/Src/candata.c.o
.PHONY : Src/candata.c.o

Src/candata.i: Src/candata.c.i

.PHONY : Src/candata.i

# target to preprocess a source file
Src/candata.c.i:
	$(MAKE) -f CMakeFiles/candata.dir/build.make CMakeFiles/candata.dir/Src/candata.c.i
.PHONY : Src/candata.c.i

Src/candata.s: Src/candata.c.s

.PHONY : Src/candata.s

# target to generate assembly for a file
Src/candata.c.s:
	$(MAKE) -f CMakeFiles/candata.dir/build.make CMakeFiles/candata.dir/Src/candata.c.s
.PHONY : Src/candata.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... candata"
	@echo "... Application"
	@echo "... Unity"
	@echo "... TestApplication"
	@echo "... Src/Application.o"
	@echo "... Src/Application.i"
	@echo "... Src/Application.s"
	@echo "... Src/candata.o"
	@echo "... Src/candata.i"
	@echo "... Src/candata.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

